project:
  type: website

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Years
        menu:
          - href: 20.qmd
            text: '2020'
      - href: about.qmd
        text: About

format:
  html:
    theme: lux
    css: styles.css
    toc: true



